### PR TITLE
added readme with images

### PR DESCRIPTION
**Pull request by PavloPopov-okta**

### CODE REVIEW

**Comment by markmoussa-okta** [comment]
I added some light edits to the readme for the "Hardening" template, and removed most of the images. The google doc didn't convert cleanly, and it would be wiser to leave out most of the images to avoid downstream maintenance overhead.

Thank you @PavloPopov-okta for all your hard work.

**Review by davidroossien-okta — CHANGES_REQUESTED** [review]
@PavloPopov-okta  please put images in a sub folder called images

**Review by davidroossien-okta — CHANGES_REQUESTED** [review]
@PavloPopov-okta okease update the links in the readme folder to point to the files in the images folder.

**Comment by PavloPopov-okta** [comment]
@davidroossien-okta Added 4 images links. @markmoussa-okta Could you pls take a look as well? It was 6 images in folder but links for 5 and 6 were used in readme file

**Review by mickjohnson-okta — APPROVED** [review]
Looks good.

**Pull request merged**
