### PR TITLE
chore: add override to force tough cookie upgrade

### PR DESCRIPTION
**Pull request by andymartin-okta**
Tough Cookie needed to be upgraded, unforuntately it's a dependency of some non-upgradable packages, so we needed ot add an override.

### CODE REVIEW

**Comment by florachen-okta** [comment]
Any test steps or test instructions?

**Comment by andymartin-okta** [comment]
> Any test steps or test instructions?

There aren't many ways to test it locally unfortunately besides using the setup scripts in the repo's readme.

**Review by IanHakes-okta — APPROVED** [review]
Is this tested? Otherwise LGTM.

**Review by florachen-okta — APPROVED** [review]
Tested image_hasher.js and lgtm (tough-cookie is a dependency of `image-hash` which seems only used in that script)

**Pull request merged**
