### PR TITLE
[OKTA-620801] feat: add new template offboard_google_workspace_users

### PR DESCRIPTION
**Pull request by runzeng-okta**
Ticket: https://oktainc.atlassian.net/browse/OKTA-620801

Change:
- add a new template: offboard_google_workspace_users

### CODE REVIEW

**Comment by runzeng-okta** [comment]
Pending doc review from both @mickjohnson-okta and @IanHakes-okta . Screenshots are inserted to workflow.json file.

**Comment by runzeng-okta** [comment]
@JirongYang-okta It's ready for review~

**Review by JirongYang-okta — DISMISSED** [review]
Merging template "Offboard Google Workspace users" into repo.
Verified 6 helper flows and screenshots submitted, flopack ready, readme file title correct.
Approved.

**Comment by runzeng-okta** [comment]
@JirongYang-okta I updated the screenshots and the workflow.flopack and workflow.json.
Can you take a look why the Circle check failed? Thanks!

**Review by JirongYang-okta — APPROVED** [review]
Helper Flow card in screenshots updated, together with flopack and workflow.json.
Changes LGTM, approved.

**Pull request merged**
